# Site settings
title: ourren
header-img: img/home-bg.jpg
email: i@ourren.com
description: "Thoughts, research and life!"
baseurl: "/en"
url: "http://www.ourren.com/en"
twitter_username: shellcodes
github_username:  ourren
facebook_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
comments: true
